### ISSUE TITLE
Convert Terraria textures to HD

### ISSUE THREAD

**Issue by Razama1234** [sullerandras/terraria-hd-textures#13]
Converting Terraria textures to HD not work at all
1. Syntax error at string 139   execute %(mkdir -p #{temp}/Content/Images)             (mkdir -p   ➜   mkdir_p) fix.
2. execute.rb:145:in `write': No such file or directory @ rb_sysopen - temp6-texture-pack/pack.json (Errno::ENOENT)
fixed by creation temp6-texture-pack folder
3. In the end .zip with only pack.json and README.txt, no any png's

cd temp6-texture-pack && zip -r ../TexturePack-v0.12-1.4.0.3.zip -0 README.txt Content pack.json && cd ..
        zip warning: name not matched: ../TexturePack-v0.12-1.4.0.3.zip
        zip warning: name not matched: Content
  adding: README.txt (172 bytes security) (stored 0%)
  adding: pack.json (172 bytes security) (stored 0%)

**Comment by FreezRider** [comment]
almost same problem, can someone help please ?

C:\Users\CaptainBananek\Desktop\Terraria.v1.4.4.9.v4\Content>ruby execute.rb
Creating zip file TexturePack-v0.12-1.4.0.3.zip with all PNG's
mkdir -p temp6-texture-pack/Content/Images
The syntax of the command is incorrect.
rm -f TexturePack-v0.12-1.4.0.3.zip
rsync -ax --delete-after temp5/ temp6-texture-pack/Content/Images/
rm -rf temp6-texture-pack/Content/Images/Backgrounds
rm -rf temp6-texture-pack/Content/Images/Misc
rm -rf temp6-texture-pack/Content/Images/UI/WorldGen
rm -rf temp6-texture-pack/Content/Images/UI/Button*
execute.rb:145:in `write': No such file or directory @ rb_sysopen - temp6-texture-pack/pack.json (Errno::ENOENT)
        from execute.rb:145:in `createTexturePack'
        from execute.rb:169:in `<main>'

**Comment by sullerandras** [comment]
I think the ruby file is outdated. I use github actions for creating the zip file, please see the commands there: https://github.com/sullerandras/terraria-hd-textures/blob/master/.github/workflows/build.yaml

You can also fork this repo and enable github actions on your fork to create the zip file.
